-- AlterTable
ALTER TABLE "User" ADD COLUMN     "activity" TEXT NOT NULL DEFAULT 'moderado',
ADD COLUMN     "age" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 170,
ADD COLUMN     "sex" TEXT NOT NULL DEFAULT 'male',
ADD COLUMN     "weight" INTEGER NOT NULL DEFAULT 70;
